robot_cfg:
  kinematics:
    asset_root_path: ''
    base_link: link_base
    collision_link_names:
    - link1
    - link2
    - link3
    - link4
    - link5
    - link6
    collision_sphere_buffer: 0.01
    collision_spheres:
      link1:
      - center:
        - 0.0
        - 0.0
        - 0.1
        radius: 0.08
      link2:
      - center:
        - 0.1
        - 0.0
        - 0.0
        radius: 0.08
      link3:
      - center:
        - 0.04
        - 0.0
        - 0.0
        radius: 0.07
      link4:
      - center:
        - 0.0
        - 0.0
        - 0.0
        radius: 0.06
      link5:
      - center:
        - 0.0
        - 0.03
        - 0.0
        radius: 0.06
      link6:
      - center:
        - 0.0
        - 0.0
        - 0.0
        radius: 0.05
    cspace:
      cspace_distance_weight:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      joint_limits:
        acceleration:
        - 6.28
        - 6.28
        - 6.28
        - 6.28
        - 6.28
        - 6.28
        jerk:
        - 100.0
        - 100.0
        - 100.0
        - 100.0
        - 100.0
        - 100.0
        lower:
        - -6.28319
        - -2.61799
        - -0.061087
        - -6.28319
        - -2.1642
        - -6.28319
        upper:
        - 6.28319
        - 2.61799
        - 5.235988
        - 6.28319
        - 2.1642
        - 6.28319
        velocity:
        - 3.14
        - 3.14
        - 3.14
        - 3.14
        - 3.14
        - 3.14
      joint_names:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      max_acceleration: 10.0
      max_jerk: 500.0
      null_space_weight:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      retract_config:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
    ee_link: link6
    self_collision_buffer:
      link1: 0.01
      link2: 0.01
      link3: 0.01
      link4: 0.01
      link5: 0.01
      link6: 0.01
      link_base: 0.01
    self_collision_ignore:
      link1:
      - link2
      - link_base
      link2:
      - link3
      - link1
      link3:
      - link4
      - link2
      link4:
      - link5
      - link3
      link5:
      - link6
      - link4
      link6:
      - link5
      link_base:
      - link1
    urdf_path: lite6.urdf
    use_global_cumul: true
