robot_cfg:
    kinematics:
        usd_path: "robot/lite6/lite6.usd"
        usd_robot_root: "/robot"
        isaac_usd_path: ""
        usd_flip_joints: {}
        usd_flip_joint_limits: []

        urdf_path: "robot/lite6/lite6.urdf"
        asset_root_path: ""

        base_link: "link_base"
        ee_link: "link_eef"
        link_names: null
        lock_joints: null
        extra_links: null

        collision_link_names: 
        - "link1"
        - "link2"
        - "link3"
        - "link4"
        - "link5"
        - "link6"
        
        collision_spheres: spheres/lite6.yml
        collision_sphere_buffer: 0.01
        extra_collision_spheres: {}
        
        self_collision_ignore:
            "link_base": ["link1", "link2"]
            "link1": ["link2", "link3", "link_base"]
            "link2": ["link3", "link4", "link1", "link_base"]
            "link3": ["link4", "link5", "link2", "link1"]
            "link4": ["link5", "link6", "link3", "link2"]
            "link5": ["link6", "link_eef", "link4", "link3"]
            "link6": ["link5", "link_eef", "link4"]
            "link_eef": ["link6", "link5"]

        self_collision_buffer:
            "link_base": 0.005
            "link1": 0.005
            "link2": 0.005
            "link3": 0.005
            "link4": 0.005
            "link5": 0.005
            "link6": 0.005
            "link_eef": 0.005
        
        use_global_cumul: true
        mesh_link_names: null

        cspace:
            joint_names: ['joint1', 'joint2', 'joint3', 'joint4', 'joint5', 'joint6']

            
            retract_config: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
            null_space_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
            cspace_distance_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
            
            max_jerk: 500.0
            max_acceleration: 15.0