# The robot description defines the generalized coordinates and how to map those
# to the underlying URDF dofs.

api_version: 1.0

# Defines the generalized coordinates. Each generalized coordinate is assumed
# to have an entry in the URDF.
# Lula will only use these joints to control the robot position.
cspace:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
default_q: [
    0.0,0.0,1.0,0.0,-0.0005,-0.0
]

acceleration_limits: [
   10,10,10,10,10,10
]

jerk_limits: [
   10000,10000,10000,10000,10000,10000
]

# Most dimensions of the cspace have a direct corresponding element
# in the URDF. This list of rules defines how unspecified coordinates
# should be extracted or how values in the URDF should be overwritten.


# Lula uses collision spheres to define the robot geometry in order to avoid
# collisions with external obstacles.  If no spheres are specified, Lula will
# not be able to avoid obstacles.

collision_spheres:
  link_base:
    - "center": [-0.013, 0.0, 0.023]
      "radius": 0.1
    - "center": [0.0, 0.0, 0.13]
      "radius": 0.05
    - "center": [0.0, 0.0, 0.197]
      "radius": 0.05
  link1:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.05
    - "center": [-0.0, 0.043, -0.0]
      "radius": 0.05
  link2:
    - "center": [0.0, -0.0, 0.083]
      "radius": 0.05
    - "center": [0.029, -0.0, 0.104]
      "radius": 0.05
    - "center": [0.077, -0.0, 0.108]
      "radius": 0.05
    - "center": [0.121, -0.0, 0.109]
      "radius": 0.05
    - "center": [0.167, -0.0, 0.104]
      "radius": 0.05
    - "center": [0.203, -0.0, 0.089]
      "radius": 0.05
    - "center": [0.207, 0.002, 0.062]
      "radius": 0.05
  link3:
    - "center": [-0.006, -0.004, -0.013]
      "radius": 0.05
    - "center": [-0.0, 0.0, 0.02]
      "radius": 0.05
    - "center": [0.053, 0.011, 0.005]
      "radius": 0.05
    - "center": [0.092, -0.013, 0.0]
      "radius": 0.05
  link4:
    - "center": [0.007, -0.009, -0.16]
      "radius": 0.05
    - "center": [-0.0, -0.0, -0.102]
      "radius": 0.05
    - "center": [0.003, -0.048, -0.093]
      "radius": 0.05
    - "center": [-0.0, -0.068, -0.046]
      "radius": 0.05
    - "center": [0.0, -0.046, 0.0]
      "radius": 0.05
  link5:
    - "center": [0.0, 0.0, -0.002]
      "radius": 0.05
    - "center": [-0.001, 0.039, -0.001]
      "radius": 0.05
  link6:
    - "center": [-0.001, 0.039, -0.001]
      "radius": 0.05
