# The robot description defines the generalized coordinates and how to map those
# to the underlying URDF dofs.

api_version: 1.0

# Defines the generalized coordinates. Each generalized coordinate is assumed
# to have an entry in the URDF.
# Lula will only use these joints to control the robot position.
cspace:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
    - joint7
default_q: [
    0.0,0.0008,0.0,-0.0002,0.0,0.0,-0.0
]

acceleration_limits: [
   10,10,10,10,10,10,10
]

jerk_limits: [
   10000,10000,10000,10000,10000,10000,10000
]

# Most dimensions of the cspace have a direct corresponding element
# in the URDF. This list of rules defines how unspecified coordinates
# should be extracted or how values in the URDF should be overwritten.

cspace_to_urdf_rules:

# Lula uses collision spheres to define the robot geometry in order to avoid
# collisions with external obstacles.  If no spheres are specified, Lula will
# not be able to avoid obstacles.

collision_spheres:
  world:
    - "center": [0.001, 0.0, 0.024]
      "radius": 0.07
    - "center": [0.0, 0.0, 0.112]
      "radius": 0.07
  link1:
    - "center": [-0.0, 0.0, -0.076]
      "radius": 0.06
    - "center": [-0.0, -0.021, -0.016]
      "radius": 0.06
    - "center": [-0.003, 0.05, -0.002]
      "radius": 0.06
    - "center": [-0.0, -0.01, -0.0]
      "radius": 0.06
  link2:
    - "center": [0.0, -0.0, 0.097]
      "radius": 0.06
    - "center": [-0.0, -0.052, 0.101]
      "radius": 0.06
    - "center": [-0.0, -0.104, 0.106]
      "radius": 0.06
    - "center": [-0.0, -0.118, 0.047]
      "radius": 0.06
    - "center": [-0.003, -0.116, -0.0]
      "radius": 0.06
    - "center": [-0.0, -0.156, -0.0]
      "radius": 0.06
  link3:
    - "center": [-0.0, -0.001, -0.059]
      "radius": 0.06
    - "center": [0.023, 0.033, 0.0]
      "radius": 0.06
    - "center": [0.042, 0.016, 0.0]
      "radius": 0.06
    - "center": [0.052, -0.043, 0.0]
      "radius": 0.06
  link4:
    - "center": [0.005, -0.01, 0.073]
      "radius": 0.06
    - "center": [0.037, -0.041, 0.062]
      "radius": 0.06
    - "center": [0.073, -0.076, 0.063]
      "radius": 0.06
    - "center": [0.072, -0.087, 0.01]
      "radius": 0.06
    - "center": [0.073, -0.14, -0.007]
      "radius": 0.06
  link5:
    - "center": [0.001, 0.004, -0.137]
      "radius": 0.06
    - "center": [0.003, 0.059, -0.075]
      "radius": 0.06
    - "center": [-0.0, 0.05, -0.001]
      "radius": 0.06
  link6:
    - "center": [-0.0, 0.002, 0.012]
      "radius": 0.06
    - "center": [0.061, 0.002, 0.006]
      "radius": 0.06
    - "center": [0.081, 0.024, 0.002]
      "radius": 0.06
  link7:
    - "center": [-0.002, -0.0, -0.037]
      "radius": 0.06
