# The robot description defines the generalized coordinates and how to map those
# to the underlying URDF dofs.

api_version: 1.0

# Defines the generalized coordinates. Each generalized coordinate is assumed
# to have an entry in the URDF.
# Lula will only use these joints to control the robot position.
cspace:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
    - joint7
    - drive_joint
    - left_inner_knuckle_joint
    - right_inner_knuckle_joint
    - right_outer_knuckle_joint
    - left_finger_joint
    - right_finger_joint
default_q: [
    -0.0,0.0011,-0.0,-1e-04,-0.0,0.0,0.0,0.0005,0.3097,0.288,0.3666,0.2164,0.5781
]

acceleration_limits: [
   10,10,10,10,10,10,10,10,10,10,10,10,10
]

jerk_limits: [
   10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000
]

# Most dimensions of the cspace have a direct corresponding element
# in the URDF. This list of rules defines how unspecified coordinates
# should be extracted or how values in the URDF should be overwritten.

cspace_to_urdf_rules:

# Lula uses collision spheres to define the robot geometry in order to avoid
# collisions with external obstacles.  If no spheres are specified, Lula will
# not be able to avoid obstacles.

collision_spheres:
  - link_base:
    - "center": [-0.0, -0.0, 0.04]
      "radius": 0.08
    - "center": [-0.0, -0.0, 0.129]
      "radius": 0.06
  - link1:
    - "center": [-0.0, 0.001, -0.074]
      "radius": 0.06
    - "center": [0.0, -0.01, -0.022]
      "radius": 0.06
    - "center": [0.002, -0.006, 0.0]
      "radius": 0.06
    - "center": [0.004, 0.04, -0.0]
      "radius": 0.06
  - link2:
    - "center": [0.001, -0.0, 0.092]
      "radius": 0.06
    - "center": [-0.007, -0.067, 0.098]
      "radius": 0.06
    - "center": [0.001, -0.12, 0.072]
      "radius": 0.06
    - "center": [0.004, -0.116, 0.002]
      "radius": 0.06
    - "center": [-0.001, -0.158, -0.0]
      "radius": 0.06
  - link3:
    - "center": [-0.008, 0.011, -0.07]
      "radius": 0.06
    - "center": [0.022, 0.03, 0.0]
      "radius": 0.06
    - "center": [0.05, 0.022, 0.0]
      "radius": 0.06
    - "center": [0.053, -0.02, 0.0]
      "radius": 0.06
  - link4:
    - "center": [0.005, -0.01, 0.062]
      "radius": 0.06
    - "center": [0.051, -0.054, 0.07]
      "radius": 0.06
    - "center": [0.073, -0.079, 0.06]
      "radius": 0.06
    - "center": [0.074, -0.089, 0.01]
      "radius": 0.06
    - "center": [0.081, -0.135, 0.0]
      "radius": 0.06
  - link5:
    - "center": [-0.001, -0.001, -0.139]
      "radius": 0.06
    - "center": [0.008, 0.073, -0.078]
      "radius": 0.06
    - "center": [0.006, 0.052, 0.014]
      "radius": 0.06
  - link6:
    - "center": [-0.0, -0.009, 0.018]
      "radius": 0.06
    - "center": [0.081, 0.013, 0.014]
      "radius": 0.06
  - link7:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.06
    - "center": [0.072, -0.007, 0.002]
      "radius": 0.06
    - "center": [-0.003, 0.001, 0.068]
      "radius": 0.06
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.03
  - left_outer_knuckle:
    - "center": [-0.006, 0.036, 0.01]
      "radius": 0.03
  - left_finger:
    - "center": [-0.003, -0.011, 0.011]
      "radius": 0.03
    - "center": [-0.007, -0.022, 0.04]
      "radius": 0.03
  - right_outer_knuckle:
    - "center": [-0.0, -0.024, 0.018]
      "radius": 0.03
    - "center": [-0.008, -0.024, 0.052]
      "radius": 0.03
    - "center": [-0.001, -0.026, 0.081]
      "radius": 0.03
